name: "thrivebookstore"

on:
  push:
    branches:
      - main  # Adjust this based on your main branch name

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2

    # Add your build steps here
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release

    - name: Publish
      run: dotnet publish -c Release -o ./Published

    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.MY_SECRET_BOOKS }}

    - name: Azure Web App Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<thrivebooks>'  # Replace with your Azure Web App name
        slot-name: 'production'  # Replace with your deployment slot name (optional)
        publish-profile: ${{ secrets.MY_SECRET_BOOKS }}
        package: ./Published
